Feature/mileage
S-OSTeam/Throw pull request #20
Opened 2023-08-25 07:34 UTC by chanil4129

entity id 삭제

2023-08-25 08:43 UTC, Hangeulkim requested changes

2023-08-25 08:43 UTC, Hangeulkim commented on api/throwapi/build.gradle
>      runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
다시 돌려놔

2023-08-25 08:43 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/Receipt.java
> +    public void modifyGifticonStatus(GifticonStatus gifticonStatus) {
단위 테스트를 위해 변경한 후 값을 반환

2023-08-25 08:43 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/dto/GifticonDto.java
> +    private UUID id;
id는 자동 생성 되는데 왜 dto로...?

2023-08-25 08:43 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/dto/GifticonDto.java
> +        this.id = id;
id는 받지도 말고 쓰지도 말것 user조회 제외

2023-08-25 08:43 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/exception/NotEnoughStockException.java
> +public class NotEnoughStockException extends RuntimeException{
runtimeException으로 에러를 만들면 에러가 안잡힘 commonException 현수가 쓴 거 참고 할 것

2023-08-25 08:43 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/repository/repoCustom/GifticonCustomRepository.java
> +public interface GifticonCustomRepository {
repo는 틀만 잡은 건가유?

2023-08-26 08:50 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/repository/repoCustom/GifticonCustomRepository.java
> +public interface GifticonCustomRepository {
이슈에 등록

2023-08-26 10:50 UTC, Hangeulkim requested changes

2023-08-26 10:50 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/exception/NotEnoughStockException.java
> +        super(code, status);
message 추가!

2023-08-26 11:05 UTC, BrownLEE99 approved these changes
good

2023-08-26 11:06 UTC, Hangeulkim requested changes

2023-08-26 11:06 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/Receipt.java
> +    private GifticonStatus gifticonStatus; //주문상태 [ORDER, CANCEL]
sold wait밖에 없는디...?

2023-08-26 11:06 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/exception/NotEnoughStockException.java
> +        super(code, status);
super("NO_SUCH_REGISTRATION_NUMBER", "국세청에 등록되지 않은 사업자등록번호입니다.", HttpStatus.BAD_REQUEST);
참고

2023-08-26 11:06 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/Receipt.java
> +            throw new IllegalStateException("현재 팔려있는 기프티콘입니다.");
기본 error쓰면 예외 처리가 안됨

2023-08-27 05:16 UTC, closed without merging