Add IPUtils.java
S-OSTeam/Throw pull request #29
Opened 2023-08-26 10:23 UTC by BrownLEE99

<img width="695" alt="스크린샷 2023-08-26 오후 7 22 06" src="https://github.com/S-OSTeam/Throw/assets/137032025/ecf897e9-1c31-4dbb-972b-c2b4d1c0d7dd">

https://blog.yevgnenll.me/posts/find-client-ip-from-http-request-header

2023-08-26 10:31 UTC, BrownLEE99 commented
RequestAtrributes 인터페이스를 통해 
ServletRequestAtrributes를 가져와서 쓰레드에 할당된 servlet request의 데이터를 받아온다.
쓰레드로 요청을 보낸 client의 정보를 수집
영한이형 강의 중에서 WAS에 request response 처리를 담당하는 얘가 누구라고 했던게 기억이 나는가? 그 누구가 바로 쓰레드인것이여

2023-08-26 10:34 UTC, BrownLEE99 commented
https://gompangs.tistory.com/entry/Spring-RequestContextHolder

pr 하러 오신분들 한번씩 읽어보고 가시오. 
저도 읽겠소

2023-08-26 10:45 UTC, Hangeulkim approved these changes

2023-08-26 10:48 UTC, Hangeulkim requested changes

2023-08-26 10:48 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/global/service/IPUtil.java
> +public class IPUtil {
ipv4로 변경

2023-08-26 10:53 UTC, BrownLEE99 commented on api/throwapi/src/main/java/sosteam/throwapi/global/service/IPUtil.java
> +public class IPUtil {
-Djava.net.preferIPv4Stack=true
를 project configuration의 VM options에 추기

2023-08-26 11:02 UTC, Hangeulkim approved these changes

2023-08-27 05:27 UTC, chanil4129 approved these changes
.

2023-08-27 05:31 UTC, merged