Feature/mileage new
S-OSTeam/Throw pull request #37
Opened 2023-08-28 10:27 UTC by chanil4129

2023-08-28 10:46 UTC, BrownLEE99 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/repository/repoCustomImpl/ReceiptCustomRepositoryImpl.java
> +        return new HashSet<>(jpaQueryFactory.selectFrom(QReceipt.receipt)
기프트콘은 static으로 가져와서 쓰던데, 여기는 Q클래스 가져다 쓰고 있음, 통일이 필요해보임
그리고 이거 두개 방법은 안해봐서 모르겠네 , 돌아감?
나는 인스턴스 생성해서 돌리긴하는데

2023-08-28 11:47 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/repository/repoCustomImpl/ReceiptCustomRepositoryImpl.java
> +        return new HashSet<>(jpaQueryFactory.selectFrom(QReceipt.receipt)
테스트 해볼라면 user_id 필요해서 수형이 코드 기다려봐야 되고, 통일 완료

2023-08-28 23:58 UTC, Hangeulkim requested changes

2023-08-28 23:58 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/Gifticon.java
> +    private String giftTraceId; // 주문 완료 후 생성되는 수신자 단위의 선물 번호
그냥 존재하는 pk id와 차이점이 뭔가유...?

2023-08-28 23:58 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/ReceiptStatus.java
> +    SALE, CONFIRMED, SOLD // 기프티콘 대기중, 기프티콘이 넘겨진 상태, 기프티콘을 사용한 상태
기프티콘을 사용한 상태를 우리가 확인이 가능 한가유?

2023-08-28 23:58 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/exception/NoSuchGifticonException.java
> +        super("No_SUCH_GIFTICON","찾고자 하는 기프티콘이 없습니다.",HttpStatus.NOT_FOUND);
코드는 무조건 대문자로

2023-08-28 23:58 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/exception/DuplicateGiftcionException.java
> +public class DuplicateGiftcionException extends CommonException {
기프티콘을 유저가 등록하는게 아닌데 중복이 있을 수 있나요?

2023-08-28 23:58 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/GifticonDeleteService.java
> +        gifticonRepository.deleteById(gifticonId);
이거 외래키 달려있어서 바로 삭제 안될 수도 있슴

2023-08-28 23:58 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ItemSearchService.java
> +        return new HashSet<>(itemRepository.findAll());
걍 find jpa 대신 search로 통일

2023-08-29 03:09 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/ReceiptStatus.java
> +    SALE, CONFIRMED, SOLD // 기프티콘 대기중, 기프티콘이 넘겨진 상태, 기프티콘을 사용한 상태
상태 확인하는 코드를 작성해야 하던디. https://giftbiz-kakao.readme.io/reference/inquirytemplategift

2023-08-29 03:20 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/exception/DuplicateGiftcionException.java
> +public class DuplicateGiftcionException extends CommonException {
삭제

2023-08-29 03:21 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/GifticonDeleteService.java
> +        gifticonRepository.deleteById(gifticonId);
그러면 어캐 해야돼요?

2023-08-29 03:22 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/GifticonCreateService.java
>      private void validateGifticon(Gifticon gifticon) {
그러네 수정할게

2023-08-29 03:25 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/Gifticon.java
> +    private String giftTraceId; // 주문 완료 후 생성되는 수신자 단위의 선물 번호
pk id는 테이블에 있는 UUID id이고, giftTraceId는 쿠폰번호라고 생각하면 될 듯? 쿠폰 조회라던가, 삭제할 때 필요한

2023-08-29 07:55 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/GifticonDeleteService.java
> +        gifticonRepository.deleteById(gifticonId);
외래키를 풀어야 함미다

2023-08-29 07:56 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/entity/ReceiptStatus.java
> +    SALE, CONFIRMED, SOLD // 기프티콘 대기중, 기프티콘이 넘겨진 상태, 기프티콘을 사용한 상태
이거 이럴꺼면 걍 구매내역 확인만 우리가 하고 기프티콘 확인이나 내역은 카톡으로 넘겨버려야 할듯

2023-08-30 01:20 UTC, BrownLEE99 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/repository/repoCustom/ItemCustomRepository.java
> +    Optional<Item> searchByProductName(String productName);
내가 이쪽 파트를 잘 모르긴한데
만약 이게 프론트에서 단순 상품 이름으로 아이템을 검색하는거라면
상품명이 무조건 다 일치 해야지 검색 결과가 1개 나오므로 사용자가 완벽하게 검색해야 딱 그 상품만 나오는거같은데,
위 방법 대신 내가 가게 이름으로 검색할때처럼 `name.contains(productName)`  해당 상품명을 "포함"하고 있는 아이템들을 반환(ex)`Optional<Set<Item>>`)해주는게 더 좋을 수도 있다는 생각을 조심히 한번 살짝 해봐도 될까요라고 여쭈어봅니다.

2023-08-30 01:23 UTC, BrownLEE99 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/repository/repoCustomImpl/ReceiptCustomRepositoryImpl.java
> +        // TODO: 2023-08-29 템플릿 변경, user 정보 추가(수형이 코드 필요)
레포단에서 서비스를 호출하는거 같은데 이거 괜찮나?? @Hangeulkim

2023-08-30 04:09 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/repository/repoCustom/ItemCustomRepository.java
> +    Optional<Item> searchByProductName(String productName);
ㅇㅈ 변경완료

2023-08-30 13:39 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/repository/repoCustomImpl/ReceiptCustomRepositoryImpl.java
> +        // TODO: 2023-08-29 템플릿 변경, user 정보 추가(수형이 코드 필요)
아뇨 레포에선 서비스를 호출해선 안됩니다...

2023-08-31 07:05 UTC, BrownLEE99 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ReceiptSearchService.java
> +    public Optional<Receipt> getReceiptById(UUID receiptId) {
search....
![image](https://github.com/S-OSTeam/Throw/assets/137032025/ffcf8434-2c1d-4865-b655-becbecd7c40a)

2023-09-03 05:22 UTC, BrownLEE99 approved these changes

2023-09-03 05:47 UTC, Hangeulkim requested changes

2023-09-03 05:47 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/controller/ItemController.java
> +        Set<ItemResponse> responses = items.stream()
이런건 of from 변환 함수 쓰기로 했읍니다

2023-09-03 05:47 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/controller/OrderController.java
> +        GifticonResponse response = new GifticonResponse();
변환 함수 쓸 것

2023-09-03 05:47 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/controller/OrderController.java
> +        String response="Delete Receipt and Gifticon: "+request.getGiftTraceId()+
이렇게 안주고 걍 id랑 date만 줘도 됨미다

2023-09-03 05:47 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/controller/response/ReceiptResponse.java
> +    private Set<GifticonResponse.GifticonInfo> gifticons; // 여러 gifticon 정보를 담는 Set
여러 군데에서 쓸거면 걍 gifticonInfo를 분리하는게 나을듯

2023-09-03 05:47 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ItemSearchService.java
> +        String templateToken = null;
굳이 여기 선언을?

2023-09-03 05:47 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ItemSearchService.java
> +    public Set<Item> searchAllItems() {
왜 임마는 옵셔널이 없나요

2023-09-03 05:47 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ReceiptCreateService.java
> +        //-----------------test 코드-----------------
test코드는 test로 옮기십쇼

2023-09-03 05:47 UTC, Hangeulkim commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ReceiptDeleteService.java
> +        // TODO: 2023-08-29 user 관계 끊는 코드 추가(수형이 코드 필요)
아직 안 된 건가요?

2023-09-03 08:58 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/controller/ItemController.java
> +        Set<ItemResponse> responses = items.stream()
고친거 맞는지 확인 부탁

2023-09-03 09:04 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/controller/OrderController.java
> +        GifticonResponse response = new GifticonResponse();
이것도 확인 부탁

2023-09-03 13:29 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/controller/response/ReceiptResponse.java
> +    private Set<GifticonResponse.GifticonInfo> gifticons; // 여러 gifticon 정보를 담는 Set
분리할까? 그렇게 여러 군데에서 쓰진 않는거 같기도 하고. 분리하는게 좋아보여?

2023-09-03 13:34 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ReceiptCreateService.java
> +        //-----------------test 코드-----------------
오케이~

2023-09-03 13:34 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ReceiptDeleteService.java
> +        // TODO: 2023-08-29 user 관계 끊는 코드 추가(수형이 코드 필요)
머지를 한번 해야 수형이꺼 참고하고 할 수 있을듯

2023-09-04 05:25 UTC, chanil4129 commented on api/throwapi/src/main/java/sosteam/throwapi/domain/order/service/ItemSearchService.java
> +        String templateToken = null;
이거 쓰는데 필요한거 아님? repo에서 끌고 올 수는 없어서

2023-09-04 06:21 UTC, Hangeulkim approved these changes

2023-09-04 06:21 UTC, merged